

# Aliases
alias ..='cd ..'
alias open='xdg-open &>/dev/null'
alias ~='cd ~'
alias dev='cd ~/dev/'
alias docs='cd ~/Documents/'
alias aliases='xdg-open &>/dev/null ~/.bash_aliases'
alias src='source ~/.bash_profile'
alias map='cd ~/dev/world-of-recurse'
alias faces='cd ~/dev/faces'
alias sol='cd ~/dev/solitude'
alias solitude='cd ~/dev/solitude'

# Git Aliases
alias add='git add'
alias co='git checkout'
alias clone='git clone'
alias cl='git clone'
alias cm='git commit -m'
alias com='git commit -m'
alias df='git diff'
alias amend='git commit --amend'
alias reset='git reset'
alias stat='git status'
alias stt='git status'
alias sta='git status'
alias tat='git status'
alias st='git status'
alias diff='git diff' 
alias log='git log' 
alias show='git show'
alias pull='git pull origin master'
alias push='git push origin master'
alias stash='git stash'
alias pop='git stash pop'
alias mas='git checkout master'
alias master='git checkout master'
alias pull_mas='git pull origin master'
alias clean='git clean -f'  
alias rebase_mas='git rebase origin/master' 
alias rebase_cont='git rebase --continue'
alias rebase_co='git rebase --continue'
alias rebase_abt='git rebase --abort'
alias rebase_ab='git rebase --abort'
alias empty='git commit -m "Empty commit" --allow-empty'
alias cm_empty='git commit -m "Empty commit" --allow-empty'
alias empty_cm='git commit -m "Empty commit" --allow-empty'

# NPM Aliases
alias start='npm run start'
alias build='npm run build'
alias deploy='npm run deploy'

# Exercism Aliases
alias submit='exercism submit src/main/**/*.*'
